mvc gog/Controllers/PaniersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc_gog.Data;
using mvc_gog.Models;

namespace mvc_gog.Controllers
{
    [Authorize]
    public class PaniersController : Controller
    {
        private readonly mvc_gogContext _context;

        public PaniersController(mvc_gogContext context)
        {
            _context = context;
        }

        // GET: Paniers
        public async Task<IActionResult> Index()
        {
            var userId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var registeredUser = _context.User.FirstOrDefault(u => u.UserID == userId);

            if (registeredUser.IsAdmin)
            {
                // return all paniers
                var paniers= await _context.Panier.Include(p=>p.User).Include(p=>p.LignePanier).ThenInclude(lp=>lp.produit).ToListAsync();
                var lignepaniers = await _context.LignePanier.Include(lp=>lp.produit).ToListAsync();
                

                var model = new CartViewModel
                {
                    Paniers = paniers,
                    LignePaniers = lignepaniers
                };
                return View(model);


            }

            else
            {
                // return only the user's paniers
                var panier = await _context.Panier.Include(p => p.User).Include(p => p.LignePanier).ThenInclude(lp => lp.produit).FirstOrDefaultAsync(p=>p.User.UserID == userId);
               
                var model = new CartViewModel
                {
                    Paniers = new List<Panier> { panier ?? new Panier()},
                    LignePaniers =panier?.LignePanier ??new List<LignePanier>()
                };
                
                
                return View(model);
            }



        }



        // GET: Paniers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Panier == null)
            {
                return NotFound();
            }
            var lignepanier = await _context.LignePanier.FindAsync(id);
            return RedirectToAction("Details", "LignePaniers", new { id = lignepanier.LignePanierID });
        }


        // GET: Paniers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Panier == null)
            {
                return NotFound();
            }

            var lignepanier = await _context.LignePanier.FindAsync(id);
            if (lignepanier == null)
            {
                return NotFound();
            }

            return RedirectToAction("Edit", "LignePaniers", new { id = lignepanier.LignePanierID });
        }




        // GET: Paniers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Panier == null)
            {
                return NotFound();
            }

            var lignepanier = await _context.LignePanier.FindAsync(id);
            if (lignepanier == null)
            {
              
                return NotFound();
            }

            return RedirectToAction("Delete", "LignePaniers", new { id = lignepanier.LignePanierID });
        }

        // POST: Paniers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            

            if (_context.Panier == null)
            {
                return Problem("Entity set 'mvc_gogContext.Panier'  is null.");
            }
            var lignepanier = await _context.LignePanier.FindAsync(id);

            if (lignepanier == null)
            {
               
                return NotFound();
            }

            return RedirectToAction("DeleteConfirmed", "LignePaniers", new { id = lignepanier.LignePanierID });
        }

        private bool PanierExists(int id)
        {
          return (_context.Panier?.Any(e => e.PanierID == id)).GetValueOrDefault();
        }
    }
}

mvc gog/Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc_gog.Data;
using mvc_gog.Models;

namespace mvc_gog.Controllers
{
    [Authorize]
    public class ProduitsController : Controller
    {
        private readonly mvc_gogContext _context;

        public ProduitsController(mvc_gogContext context)
        {
            _context = context;
        }

        // GET: Produits
        public async Task<IActionResult> Index()
        {
              return _context.Produit != null ? 
                          View(await _context.Produit.ToListAsync()) :
                          Problem("Entity set 'mvc_gogContext.Produit'  is null.");
        }


        // GET: Produits but for clients

        public async Task<IActionResult> List()
        {
            return _context.Produit != null ?
                        View(await _context.Produit.ToListAsync()) :
                        Problem("Entity set 'mvc_gogContext.Produit'  is null.");
        }


        // GET: Produits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Produit == null)
            {
                return NotFound();
            }

            var produit = await _context.Produit
                .FirstOrDefaultAsync(m => m.ProduitID == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        // GET: Produits/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProduitID,PanierID,imageurl,Prodname,Price,Dateofcreation,desc,Autor")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produit);
        }

        // GET: Produits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Produit == null)
            {
                return NotFound();
            }

            var produit = await _context.Produit.FindAsync(id);
            if (produit == null)
            {
                return NotFound();
            }
            return View(produit);
        }

        // POST: Produits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProduitID,PanierID,imageurl,Prodname,Price,Dateofcreation,desc,Autor")] Produit produit)
        {
            if (id != produit.ProduitID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProduitExists(produit.ProduitID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produit);
        }

        // GET: Produits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Produit == null)
            {
                return NotFound();
            }

            var produit = await _context.Produit
                .FirstOrDefaultAsync(m => m.ProduitID == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        // POST: Produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Produit == null)
            {
                return Problem("Entity set 'mvc_gogContext.Produit'  is null.");
            }
            var produit = await _context.Produit.FindAsync(id);
            if (produit != null)
            {
                _context.Produit.Remove(produit);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProduitExists(int id)
        {
          return (_context.Produit?.Any(e => e.ProduitID == id)).GetValueOrDefault();
        }




        public async Task<IActionResult> AddToPanier(int id, int Quantite)
        {
            //GET THE LOGGED IN USER ID 
            var userId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);

            // GET THE PRODUCT FROM DB
            var produit = await _context.Produit.FindAsync(id);

            // check if product exists and the quantity is valid
            if (produit == null || Quantite <= 0)
            {
                return RedirectToAction("Index", "Paniers");
            }

            // check if user already has a PANIER
            var panier = await _context.Panier.Include(p => p.LignePanier).FirstOrDefaultAsync(p => p.User.UserID == userId);

            if (panier == null)
            {
                panier = new Panier();
                var usr =  _context.User.FirstOrDefaultAsync(p => p.UserID == userId);
                panier.User = usr.Result;

                panier.NbreArticle += Quantite;

                panier.Total += Quantite * (double)produit.Price;

                //create new line item for the PANIER
                var lignePanier = new LignePanier { ProduitID = produit.ProduitID, NbreArticle = Quantite, Total = Quantite * produit.Price, produit=produit};
                panier.LignePanier = new List<LignePanier> { lignePanier };
               
                _context.Panier.Add(panier);
                await _context.SaveChangesAsync();
            }
            else
            {
                // check if product is already in the PANIER
                var existingLignePanier = panier.LignePanier.FirstOrDefault(lp => lp.ProduitID == id);

                if (existingLignePanier != null)
                {
                    // update the panier and lignepanier
                    existingLignePanier.NbreArticle += Quantite;
                    existingLignePanier.Total += Quantite * (double)produit.Price;

                    panier.NbreArticle += Quantite;
                    panier.Total += Quantite * (double)produit.Price;
                    
                    _context.Update(panier);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    // add new product to the lignepanier
                    var lignePanier = new LignePanier { ProduitID = produit.ProduitID, NbreArticle = Quantite, Total = Quantite * produit.Price, produit = produit };


                    panier.LignePanier.Add(lignePanier);

                    panier.NbreArticle += Quantite;
                    panier.Total += Quantite * (double)produit.Price;
                    _context.Update(panier);
                    await _context.SaveChangesAsync();
                }
            }

            return RedirectToAction("Index", "Paniers");
        }



    }
}

mvc gog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GOD of GAMES </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/css/footer.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/card.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Reem+Kufi+Ink&display=swap" rel="stylesheet">

</head>
<body>





    <div class="wrapper">

        <!-- Top Header Code -->
        <nav>
            <div class="menu">
                <!-- logo -->
                <div class="logo">
                    <img src="~/css/Images/GodLogo.png" />
                </div>

                <!-- Menu Bar Code -->
                <input type="checkbox" id="check">
                <label for="check" class="checkbtn">
                    <i class="fas fa-bars"></i>
                </label>
                <ul>
                    <li>
                        <div class="MobNavBtns">
                            <button>Play Now</button>
                        </div>
                    </li>


                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (User.IsInRole("admin"))
                        {

                            <li> <a class="nav-link " asp-area="" asp-controller="Produits" asp-action="Index">Games</a></li>
                            <li> <a class="nav-link " asp-area="" asp-controller="Produits" asp-action="Create">add Games</a></li>        

                            <li> <a class="nav-link " asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                            <li> <a class="nav-link " asp-area="" asp-controller="Users" asp-action="Create">add Users</a></li>

                            <li> <a class="nav-link " asp-area="" asp-controller="Paniers" asp-action="Index">Carts</a></li>
                            

                           @* <li> <a class="nav-link " asp-area="" asp-controller="LignePaniers" asp-action="Index"> cart lists</a></li> *@
                                
                           //   /**/  """  """  @**@  <!---->  #  {/* */}

                            <li class="LOGOUTbtns"> <button><a class="nav-link" asp-area="" asp-controller="Users" asp-action="Logout"> Logout </a></button> </li>


                        }
                        @if (User.IsInRole("user"))
                        {

                            <li> <a class="nav-link " asp-area="" asp-controller="Produits" asp-action="List">Games</a></li>
                            <li> <a class="nav-link " asp-area="" asp-controller="Paniers" asp-action="Index">Cart</a></li>

                            <li class="LOGOUTbtns"> <button><a class="nav-link" asp-area="" asp-controller="Users" asp-action="Logout"> Logout </a></button> </li>

                        }
                    }

                   
                   

                </ul>
                <!-- Menu Bar Code End -->
                <!-- Header Button Code -->
         
                <!-- Header Button Code End -->
            </div>
        </nav>
        <!-- Top Header Code End -->


    </div>


    <div class="row d-flex justify-content-center ">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>


    <footer class="myfooter footer-distributed">

        <div class="footer-right">

            <a href="https://yahya.rabii.me/"><i class="fa fa-globe"></i></a>
            <a href="https://twitter.com/_NOXIDEUS_"><i class="fa fa-twitter"></i></a>
            <a href="https://github.com/Yahya-rabii"><i class="fa fa-github"></i></a>
            <a href=“tel:+212701242563”><i class="fa fa-phone"></i></a>
        </div>

        <div class="footer-left">

          @if (User.Identity.IsAuthenticated)
            {
                @if (User.IsInRole("admin"))
                {
                    <p class="footer-links">

                        <a class="nav-link " asp-area="" asp-controller="Paniers" asp-action="Index">Carts</a>
                        <a class="nav-link " asp-area="" asp-controller="Produits" asp-action="Index">Games</a>
                        <a class="nav-link " asp-area="" asp-controller="Users" asp-action="Index">Users</a>


                    </p>
                }
                else
                {
                    <p class="footer-links">
                    <a class="nav-link " asp-area="" asp-controller="Paniers" asp-action="Index">Carts</a>
                    <a class="nav-link " asp-area="" asp-controller="Produits" asp-action="List">Games</a>
                    </p>

                }
            }
            <p>NOXIDEUS &copy; 2023</p>
        </div>

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/login.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>